services:
  api:
    build: .
    ports:
      - "8080:8080"
    links:
      - selenium
  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g